version: '3.8'

services:
  database_lokal:
    image: postgres:15
    container_name: ${ENV_CONTAINER_NAME}
    restart: always
    environment:           
      POSTGRES_USER: ${ENV_DB_USER}
      POSTGRES_PASSWORD: ${ENV_DB_PASSWORD}
      POSTGRES_DB: ${ENV_DB_NAME}
    ports:
      - "5432:5432"